"""The prop scatter -- Python twin of src/shared/Core/ScatterCore.luau.

KEEP THE TWO IN STEP. The game scatters props with the Luau module when a map
is generated; the Blender scene previews a run with this file. Every DECISION
(how many props, which, where, which turn) is made with integers from the same
32-bit generator, so a seed gives the same scatter in both. Floats appear only
in what is output (jitter, scale, rotation), never in a choice.

SPAWN POINTS -- per chunk, generated by the kit (build_sky_citadel_scenarios.py)
A grid, one point every GRID studs, of places a prop could stand: ray-cast onto
the real deck, never in the walking line between openings. Each point is six
characters of URL-safe base64:
  c0  gx            grid column, x = ORIGIN + GRID * gx   (Blender x)
  c1  gz            grid row,    y = ORIGIN + GRID * gz   (Blender y)
  c2  yq >> 2       height in quarter studs, y = yq / 4 - 8
  c3  (yq & 3) << 4 | r        r: studs of clear, flat deck around it (0..15)
  c4  wall << 5 | dir << 2 | tower << 1
        wall   within WALL studs of a deck edge
        dir    the inward direction of that edge, in eighths of a turn
        tower  at the foot of a tower or spire
  c5  head      headroom in 2-stud steps (15 = 30 or more)
Air points (for things that float) are four characters:
  c0 gx, c1 gz, c2 z0 + 32 (studs), c3 z1 - z0 (studs): a band a float of radius
  AIR_R may hang anywhere in.
"""

MASK = 0xFFFFFFFF
ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_"
INDEX = {c: i for i, c in enumerate(ALPHABET)}
GRID = 6
ORIGIN = -126
WALL = 7.0
AIR_GRID = 16
AIR_R = 3.0
GAP = 1.0            # studs kept between any two scattered props


def imul(a, b):
    a &= MASK
    b &= MASK
    al, ah = a & 0xFFFF, a >> 16
    bl, bh = b & 0xFFFF, b >> 16
    return (al * bl + (((ah * bl + al * bh) & 0xFFFF) << 16)) & MASK


def fnv(text):
    h = 2166136261
    for byte in text.encode("utf-8"):
        h ^= byte
        h = imul(h, 16777619)
    return h


class Rng:
    """mulberry32: small, fast, and exactly reproducible in Luau."""

    def __init__(self, seed):
        self.a = seed & MASK

    def next(self):
        self.a = (self.a + 0x6D2B79F5) & MASK
        t = self.a
        t = imul(t ^ (t >> 15), t | 1)
        t = (t ^ ((t + imul(t ^ (t >> 7), t | 61)) & MASK)) & MASK
        return (t ^ (t >> 14)) & MASK

    def below(self, n):
        return self.next() % n

    def range(self, lo, hi):
        return lo + self.below(hi - lo + 1)


# ---- encoding (the kit writes these; the game only decodes) ----------------

def encode_point(gx, gz, y, r, wall, direction, tower, head):
    yq = max(0, min(255, int(round((y + 8.0) * 4))))
    r = max(0, min(15, int(r)))
    head = max(0, min(15, int(head)))
    cs = [gx, gz, yq >> 2, ((yq & 3) << 4) | r, (int(wall) << 5) | ((direction & 7) << 2) | (int(tower) << 1), head]
    return "".join(ALPHABET[c] for c in cs)


def encode_air(gx, gz, z0, z1):
    return "".join(ALPHABET[c] for c in (gx, gz, max(0, min(63, int(z0) + 32)), max(0, min(63, int(z1 - z0)))))


def decode_points(s):
    out = []
    for i in range(0, len(s), 6):
        c = [INDEX[ch] for ch in s[i:i + 6]]
        yq = (c[2] << 2) | (c[3] >> 4)
        out.append({"gx": c[0], "gz": c[1], "yq": yq, "r": c[3] & 15, "wall": c[4] >> 5,
                    "dir": (c[4] >> 2) & 7, "tower": (c[4] >> 1) & 1, "head": c[5]})
    return out


def decode_air(s):
    out = []
    for i in range(0, len(s), 4):
        c = [INDEX[ch] for ch in s[i:i + 4]]
        out.append({"gx": c[0], "gz": c[1], "z0": c[2] - 32, "span": c[3]})
    return out


# ---- the scatter ---------------------------------------------------------------

def rule_ok(rule, pt, wind):
    if rule == "Any":
        return True
    if rule == "Wall":
        return pt["wall"] == 1
    if rule == "Open":
        return pt["wall"] == 0
    if rule == "Base":
        return pt["tower"] == 1
    if rule == "Lee":
        return pt["wall"] == 1 and (pt["dir"] - wind) % 8 in (0, 1, 7)
    return False


def scatter(points_s, air_s, pool, kinds, seed, key):
    """-> list of placements: dict(kind, x, y, z (Blender), yaw (deg), scale)."""
    rng = Rng(fnv("%d|%s" % (seed, key)))
    pts = decode_points(points_s)
    air = decode_air(air_s) if air_s else []
    n = len(pts)
    out = []
    if n == 0:
        return out
    grid = {(p["gx"], p["gz"]): p for p in pts}
    dens = rng.range(pool["Density"][0], pool["Density"][1])          # per mille
    target = (n * dens) // (pool["PointsPer"] * 1000)
    target = max(pool["Min"], min(pool["Max"], target))
    wind = rng.below(8)
    taken = []                                                         # (gx, gz, radius)

    def fits(pt, rad):
        for gx, gz, rr in taken:
            dx = (pt["gx"] - gx) * GRID
            dz = (pt["gz"] - gz) * GRID
            lim = rr + rad + GAP
            if dx * dx + dz * dz < lim * lim:
                return False
        return True

    def try_place(entry, pick, tries):
        names = entry["Kinds"]
        name = names[rng.below(len(names))]
        k = kinds[name]
        sc = rng.range(entry["Scale"][0], entry["Scale"][1])
        rad = k["R"] * sc / 1000
        hgt = k["H"] * sc / 1000
        for _ in range(tries):
            pt = pick()
            if pt is None:
                continue
            if not rule_ok(entry["Rule"], pt, wind):
                continue
            if pt["r"] < rad or (pt["head"] < 15 and pt["head"] * 2 < hgt):
                continue
            if not fits(pt, rad):
                continue
            if entry["Align"] == "Wall" and pt["wall"] == 1:
                yaw = pt["dir"] * 45 + 90 + (rng.below(2) * 180)
            else:
                yaw = rng.below(360)
            slack = min(2.0, pt["r"] - rad)
            jx = (rng.below(2001) - 1000) / 1000 * slack
            jz = (rng.below(2001) - 1000) / 1000 * slack
            taken.append((pt["gx"], pt["gz"], rad))
            out.append({"kind": name, "x": ORIGIN + GRID * pt["gx"] + jx, "y": ORIGIN + GRID * pt["gz"] + jz,
                        "z": pt["yq"] / 4 - 8, "yaw": yaw, "scale": sc / 1000})
            return pt
        return None

    def anywhere():
        return pts[rng.below(n)]

    for g in pool["Groups"]:
        if len(out) >= target:
            break
        if rng.below(100) >= g["Chance"]:
            continue
        core = try_place(g["Core"], anywhere, 24)
        if core is None:
            continue
        for m in g["Members"]:
            lo = (m["Ring"][0] + GRID - 1) // GRID
            hi = m["Ring"][1] // GRID

            def ring(core=core, lo=lo, hi=hi):
                dx = rng.range(-hi, hi)
                dz = rng.range(-hi, hi)
                d2 = dx * dx + dz * dz
                if d2 < lo * lo or d2 > hi * hi:
                    return None
                return grid.get((core["gx"] + dx, core["gz"] + dz))

            for _ in range(rng.range(m["Count"][0], m["Count"][1])):
                try_place(m, ring, 10)

    singles = pool["Singles"]
    total = sum(s["Weight"] for s in singles)
    attempts = 0
    while singles and len(out) < target and attempts < target * 8 + 20:
        attempts += 1
        roll = rng.below(total)
        for s in singles:
            roll -= s["Weight"]
            if roll < 0:
                break
        try_place(s, anywhere, 2)

    # floats, apart from the ground props: they only keep clear of each other
    floating = []
    for a in pool["Air"]:
        if not air:
            break
        names = a["Kinds"]
        for _ in range(rng.range(a["Count"][0], a["Count"][1])):
            name = names[rng.below(len(names))]
            for _t in range(6):
                ap = air[rng.below(len(air))]
                if any((ap["gx"] - gx) ** 2 + (ap["gz"] - gz) ** 2 < 1 for gx, gz in floating):
                    continue
                z = ap["z0"] + rng.below(ap["span"] + 1)
                floating.append((ap["gx"], ap["gz"]))
                out.append({"kind": name, "x": ORIGIN + AIR_GRID * ap["gx"], "y": ORIGIN + AIR_GRID * ap["gz"],
                            "z": z, "yaw": rng.below(360), "scale": 1.0})
                break
    return out
