"""crossroads_layout.json -> src/shared/Content/Hub/CrossroadsV2.luau

Converts Blender coordinates (x, y north, z up) to Roblox hub coordinates
(x, z, -y): north is -Z. Every centre is relative to the hub floor at the
Engine, so HubBuilder adds the hub anchor and nothing else.

    python assets/source/hub/crossroads/make_layout_luau.py
"""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[4]
SRC = ROOT / "assets/export/hub/crossroads/crossroads_layout.json"
OUT = ROOT / "src/shared/Content/Hub/CrossroadsV2.luau"


def v3(c):
    return f"Vector3.new({c[0]:.3f}, {c[2]:.3f}, {-c[1]:.3f})"


def main():
    d = json.loads(SRC.read_text(encoding="utf-8"))
    out = ["--!strict",
           "-- GENERATED by assets/source/hub/crossroads/make_layout_luau.py from",
           "-- crossroads_layout.json. Do not edit by hand: rebuild the hub and regenerate.",
           "--",
           "-- The Crossroads v2 (2026-09-23): each MeshPart's bounding-box centre in hub",
           "-- coordinates (studs, north = -Z, floor at the Engine = 0), what moves and",
           "-- how, and the named gameplay points.",
           "",
           "return {"]
    for group, key in (("Hub", "Pieces"), ("Animated", "Animated")):
        out.append(f"\t{key} = {{")
        for name, p in sorted(d["pieces"].items()):
            if p["group"] != group:
                continue
            extra = f', Kind = "{p["anim"]}", Host = "{p["host"]}"' if group == "Animated" else ""
            out.append(f'\t\t{name} = {{ Centre = {v3(p["centre"])}{extra} }},')
        out.append("\t},")
    for group, key in (("Backdrop", "Backdrop"), ("Orbiters", "Orbiters")):
        out.append(f"\t{key} = {{")
        for name, p in sorted(d["pieces"].items()):
            if p["group"] == group and not p.get("sub"):
                s = p["size"]
                out.append(f'\t\t{name} = {{ Size = Vector3.new({s[0]:.1f}, {s[2]:.1f}, {s[1]:.1f}) }},')
        out.append("\t},")

    # A sky prop's moving pieces, in the prop's own frame AS IMPORTED (the
    # importer's half turn negates X and Z): each piece's centre and hinge as
    # offsets from the body's centre, and its axis.
    def local(c, body):
        dx, dy, dz = c[0] - body[0], c[2] - body[2], -(c[1] - body[1])
        return (-dx, dy, -dz)

    out.append("\tOrbiterParts = {")
    for name, p in sorted(d["pieces"].items()):
        sub = p.get("sub")
        if p["group"] != "Orbiters" or not sub:
            continue
        body = d["pieces"][sub["parent"]]["centre"]
        o, h = local(p["centre"], body), local(sub["hinge"], body)
        ax = sub["axis"]
        axis = (-ax[0], ax[2], ax[1])
        out.append(f'\t\t{name} = {{ Parent = "{sub["parent"]}", Kind = "{sub["kind"]}", '
                   f'Offset = Vector3.new({o[0]:.3f}, {o[1]:.3f}, {o[2]:.3f}), '
                   f'Hinge = Vector3.new({h[0]:.3f}, {h[1]:.3f}, {h[2]:.3f}), '
                   f'Axis = Vector3.new({axis[0]:.4f}, {axis[1]:.4f}, {axis[2]:.4f}), '
                   f'Amp = {sub["amp"]}, Rate = {sub["rate"]}, Phase = {sub["phase"]} }},')
    out.append("\t},")
    out.append("\tAnchors = {")
    for name, c in sorted(d["anchors"].items()):
        out.append(f"\t\t{name} = {v3(c)},")
    out.append("\t},")
    out.append("}")
    OUT.write_text("\n".join(out) + "\n", encoding="utf-8", newline="\n")
    print("wrote", OUT.relative_to(ROOT))


if __name__ == "__main__":
    main()
