"""crossroads_layout.json -> src/shared/Content/Hub/CrossroadsV2.luau

Converts Blender coordinates (x, y north, z up) to Roblox hub coordinates
(x, z, -y): north is -Z. Every centre is relative to the hub floor at the
Engine, so HubBuilder adds the hub anchor and nothing else.

    python assets/source/hub/crossroads/make_layout_luau.py
"""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[4]
SRC = ROOT / "assets/export/hub/crossroads/crossroads_layout.json"
OUT = ROOT / "src/shared/Content/Hub/CrossroadsV2.luau"


def v3(c):
    return f"Vector3.new({c[0]:.3f}, {c[2]:.3f}, {-c[1]:.3f})"


def main():
    d = json.loads(SRC.read_text(encoding="utf-8"))
    out = ["--!strict",
           "-- GENERATED by assets/source/hub/crossroads/make_layout_luau.py from",
           "-- crossroads_layout.json. Do not edit by hand: rebuild the hub and regenerate.",
           "--",
           "-- The Crossroads v2 (2026-09-23): each MeshPart's bounding-box centre in hub",
           "-- coordinates (studs, north = -Z, floor at the Engine = 0), what moves and",
           "-- how, and the named gameplay points.",
           "",
           "return {"]
    for group, key in (("Hub", "Pieces"), ("Animated", "Animated")):
        out.append(f"\t{key} = {{")
        for name, p in sorted(d["pieces"].items()):
            if p["group"] != group:
                continue
            extra = f', Kind = "{p["anim"]}", Host = "{p["host"]}"' if group == "Animated" else ""
            out.append(f'\t\t{name} = {{ Centre = {v3(p["centre"])}{extra} }},')
        out.append("\t},")
    for group, key in (("Backdrop", "Backdrop"), ("Orbiters", "Orbiters")):
        out.append(f"\t{key} = {{")
        for name, p in sorted(d["pieces"].items()):
            if p["group"] == group:
                s = p["size"]
                out.append(f'\t\t{name} = {{ Size = Vector3.new({s[0]:.1f}, {s[2]:.1f}, {s[1]:.1f}) }},')
        out.append("\t},")
    out.append("\tAnchors = {")
    for name, c in sorted(d["anchors"].items()):
        out.append(f"\t\t{name} = {v3(c)},")
    out.append("\t},")
    out.append("}")
    OUT.write_text("\n".join(out) + "\n", encoding="utf-8", newline="\n")
    print("wrote", OUT.relative_to(ROOT))


if __name__ == "__main__":
    main()
