"""Version new asset mappings and reconstruct the bounded Studio review.

This writes no production Content or accepted source. The default Rojo tree is
copied into an opt-in review project; the main testing place remains untouched.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[5]
HERE = Path(__file__).resolve().parent
OUT = Path('E:/BlenderAIProjects/Runtime/Emberfall_Batch2')


def main():
    fixture = ROOT / 'tools/studio/emberfall_batch2'
    source = json.loads((OUT / 'source_export_manifest.json').read_text())
    review = json.loads((OUT / 'review_export_manifest.json').read_text())
    data = json.loads((OUT / 'review_data.json').read_text())
    mappings = []
    pending = []
    source_ids, review_ids = {}, {}
    for category, paths, target in (
        ('source', ['source_visual_0', 'source_visual_1', 'source_collision'], source_ids),
        ('review', ['review_visual_' + str(i) for i in range(len(review['files']))], review_ids),
    ):
        for name in paths:
            if not (OUT / (name + '_mapping.json')).exists():
                pending.append(name)
                continue
            m = json.loads((OUT / (name + '_mapping.json')).read_text())
            mappings.append(dict(category=category, file=name, modelAssetId=m['modelAssetId'], operationId=m['operationId']))
            for p in m['meshParts']:
                assert p['name'] not in target, p['name']
                target[p['name']] = p['meshId']
    assert len(source_ids) == len(source['assets'])
    ledger = dict(models=mappings, sources=source['assets'], sourceIds=source_ids, reviewIds=review_ids, reviewOnly=True, pendingReviewFiles=pending)
    (HERE / 'asset_mapping.json').write_text(json.dumps(ledger, indent=2) + '\n')
    if pending:
        print('REVIEW_INTEGRATION_HOLD', pending)
        return
    assert len(review_ids) == len(review['records'])
    bounds_path=OUT/'review_bounds_manifest.json'
    if bounds_path.exists():
        bounds=json.loads(bounds_path.read_text())
        for i,f in enumerate(bounds['files']):
            m=json.loads((OUT/f'review_bounds_{i}_mapping.json').read_text())
            assert len(m['meshParts'])==f['meshes']
            mappings.append(dict(category='review_bounds',file='review_bounds_'+str(i),modelAssetId=m['modelAssetId'],operationId=m['operationId']))
            for p in m['meshParts']:review_ids[p['name']]=p['meshId']
        data['assets']=[r for r in data['assets'] if r['key'] not in bounds['replaced']]+bounds['records']
        ledger['reviewIds']=review_ids
        ledger['boundsRepair']=dict(replaced=bounds['replaced'],newRecords=len(bounds['records']),triangles=bounds['triangles'])
        (HERE/'asset_mapping.json').write_text(json.dumps(ledger,indent=2)+'\n')
    cell_path=OUT/'review_cell_manifest.json'
    if cell_path.exists():
        cell=json.loads(cell_path.read_text())
        for i,f in enumerate(cell['files']):
            m=json.loads((OUT/f'review_cell_{i}_mapping.json').read_text())
            assert len(m['meshParts'])==f['meshes']
            mappings.append(dict(category='review_cell',file='review_cell_'+str(i),modelAssetId=m['modelAssetId'],operationId=m['operationId']))
            for p in m['meshParts']:review_ids[p['name']]=p['meshId']
        data['assets']=[r for r in data['assets'] if r['key'] not in cell['replaced']]+cell['records']
        ledger['cellRepair']=dict(replaced=cell['replaced'],newRecords=len(cell['records']),triangles=cell['triangles'])
        (HERE/'asset_mapping.json').write_text(json.dumps(ledger,indent=2)+'\n')
    old = json.loads((ROOT / 'tools/studio/emberfall_walkthrough/WalkthroughData.luau').read_text().split('[==[')[1].split(']==]')[0])
    data['ids'] = {r['key']: review_ids.get(r['key'], source_ids.get(r['key'], old['ids'].get(r['key']))) for r in data['assets']}
    data['sourceIds'] = source_ids
    data['sourceVisuals'] = [r for r in source['assets'] if r['role'] != 'collision']
    assert all(data['ids'].values())
    fixture.mkdir(parents=True, exist_ok=True)
    (fixture / 'ReviewData.luau').write_text('--!strict\n-- Generated by integrate_review.py; fixed semantic appearance, opt-in Studio only.\nreturn game:GetService("HttpService"):JSONDecode([==[' + json.dumps(data, separators=(',', ':')) + ']==])\n')

    # Retain the accepted adapter's loader/placement logic. Change only fixture
    # identity, canonical-template lookup and the baked presentation inputs.
    code = (ROOT / 'tools/studio/emberfall_walkthrough/OwnerWalkthrough.server.luau').read_text()
    code = code.replace('EmberfallWalkthrough', 'EmberfallBatch2Review').replace('EmberfallOwnerWalkthrough', 'EmberfallBatch2Review')
    code = code.replace('local scenery: any = require(RS.EmberfallSceneryData)\n', '')
    code = code.replace('for _, chunk in data.kit do\n\tlocal model', 'for _, templateName in data.collisionTemplates do\n\tlocal model')
    code = code.replace('model.Name = chunk.CollisionTemplate', 'model.Name = templateName')
    code = code.replace('templates.Parent = kits', 'templates.Parent = SS')
    code = code.replace('local loaded =', 'templates.Parent = kits\nlocal loaded =')
    code = code.replace('templates[data.kit[record.chunk].CollisionTemplate]', 'templates[data.collisionTemplates[record.chunk]]')
    start = code.index('for _, record in data.assets do\n\tif record.role ~= "collision"')
    end = code.index('local layout: any', start)
    code = code[:start] + '''local requests = {}
for _, record in data.assets do
    if record.role ~= "collision" then
        table.insert(requests, { Key = record.key, Role = "VISUAL_ONLY" })
    end
end
workspace:SetAttribute("EmberfallBatch2ReviewStatus", "Preparing baked production visuals")
local prepared = assets:prepareMany(requests)
assert(prepared.ok, prepared.err)
local sourcePreparation = Preparation.new({
    assetId = function(key: string) return data.sourceIds[key] end,
}, { AssetPreparationWorkers = workers, AssetPreparationDiagnostics = true })
local sourceRequests = {}
for _, record in data.sourceVisuals do
    table.insert(sourceRequests, { Key = record.key, Role = "VISUAL_ONLY" })
end
local sourcePrepared = sourcePreparation:prepareMany(sourceRequests)
assert(sourcePrepared.ok, sourcePrepared.err)
workspace:SetAttribute("EmberfallBatch2SourceVisualsResolved", #sourceRequests)
workspace:SetAttribute("EmberfallBatch2SourcePreparation", game:GetService("HttpService"):JSONEncode(sourcePreparation:stats()))
''' + code[end:]
    code = code.replace('loaded.UsedMeshes == 9', 'loaded.UsedMeshes == #data.rows')
    code = code.replace('and record.role ~= "scenery" then', 'then')
    code = code.replace('''		if record.role == "road" then
			p.Color = Color3.new(0.461356, 0.381092, 0.2717)
		end
		if record.role == "fire" then
			p.Color = Color3.new(0.906332, 0.537099, 0.151704)
		end
''', '')
    start = code.index('-- Ordinary assembled scenery')
    end = code.index('-- Roblox FBX import', start)
    code = code[:start] + '''world:SetAttribute("SceneryEditableMeshes", 0)
world:SetAttribute("SceneryRecolourSeconds", 0)
world:SetAttribute("ReviewOnly", true)
world:SetAttribute("VisualParts", #requests)
world:SetAttribute("UniqueCollisionParts", #queue)
''' + code[end:]
    code = code.replace('world:SetAttribute("CollisionParts", #queue)', 'local collisionParts = 0\nfor _, part in world:GetDescendants() do\n    if part:IsA("MeshPart") and part.CanCollide then collisionParts += 1 end\nend\nworld:SetAttribute("CollisionParts", collisionParts)')
    code = code.replace('world:SetAttribute("TerrainReady", true)', 'world:SetAttribute("TerrainReady", true)\nworld:SetAttribute("UsedMeshes", loaded.UsedMeshes)\nworld:SetAttribute("FallbackFloors", loaded.FloorCount)\nworld:SetAttribute("AssetPreparation", game:GetService("HttpService"):JSONEncode(assets:stats()))')
    code = code[:code.rindex('print(')] + 'print("[EmberfallBatch2Review] 24 real source placements, zero fallback floors, baked semantic appearance")\n'
    (fixture / 'Batch2Review.server.luau').write_text(code)
    client = (ROOT / 'tools/studio/emberfall_walkthrough/OwnerWalkthroughAppearance.client.luau').read_text()
    client = client.replace('EmberfallWalkthrough', 'EmberfallBatch2Review').replace('EmberfallOwnerWalkthrough', 'EmberfallBatch2Review')
    client = client.replace('Layout1Snapshot', 'BoundedCombined2SemanticSnapshot').replace('Layout1 • scenery continuity candidate', 'Batch 2 • 24-placement repeated-source review')
    client = client.replace('Layout1', 'Batch 2').replace('scenery continuity candidate', '24-placement repeated-source review')
    client = client.replace('-- Owner-authorized Layout1 snapshot. Production EditableMesh allocation remains open.', '-- Bounded opt-in Studio production review; no runtime EditableMesh allocation.')
    (fixture / 'Batch2ReviewAppearance.client.luau').write_text(client)
    project = json.loads((ROOT / 'default.project.json').read_text())
    project['name'] = 'EmberfallBatch2ProductionReview'
    project['tree']['ReplicatedStorage']['EmberfallBatch2ReviewData'] = {'$path': 'tools/studio/emberfall_batch2/ReviewData.luau'}
    project['tree']['ServerScriptService']['EmberfallBatch2Review'] = {'$path': 'tools/studio/emberfall_batch2/Batch2Review.server.luau'}
    project['tree']['StarterPlayer']['StarterPlayerScripts']['EmberfallBatch2ReviewAppearance'] = {'$path': 'tools/studio/emberfall_batch2/Batch2ReviewAppearance.client.luau'}
    (ROOT / 'emberfall-batch2-review.project.json').write_text(json.dumps(project, indent=2) + '\n')
    print('MAPPING_PASS', len(source_ids), len(review_ids), len(data['assets']))


if __name__ == '__main__':
    main()
