"""Regenerate INDEX_MAP.md, the generated file map that INDEX.md (the hand-written guide) points into.

    python tools/gen_index.py          # rewrite INDEX_MAP.md
    python tools/gen_index.py --check  # exit 1 if INDEX_MAP.md is stale (CI)

For every tracked file: its path, a one-line description (the file's own header comment / docstring / first
heading), and for code the exact LINE NUMBERS of every function / module entry point; for docs, every heading.
Binary assets are listed per folder. Deterministic: same repo -> same output, so CI can diff it.
"""
import os, re, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MAP = os.path.join(ROOT, "INDEX_MAP.md")
TEXT = (".luau", ".lua", ".py", ".md", ".json", ".toml", ".sh", ".txt")
MAX_SYMBOLS = 40


def tracked():
    out = subprocess.run(["git", "ls-files", "--cached", "--others", "--exclude-standard"], cwd=ROOT, capture_output=True, text=True, check=True).stdout
    return sorted(set(p for p in out.splitlines() if p and not p.endswith(".gitkeep") and p != "INDEX_MAP.md" and os.path.exists(os.path.join(ROOT, p))))


def last_changed():
    """{path: YYYY-MM-DD of the last commit touching it}, from one `git log` call (needs full history)."""
    out = subprocess.run(["git", "log", "--format=@%cs", "--name-only"], cwd=ROOT, capture_output=True,
                         text=True, check=True).stdout
    dates, day = {}, ""
    for line in out.splitlines():
        if line.startswith("@"):
            day = line[1:]
        elif line and line not in dates:
            dates[line] = day
    return dates


DATE = re.compile(r" \u00b7 (\d{4}-\d\d-\d\d|new)$", re.M)


def read(p):
    try:
        with open(os.path.join(ROOT, p), encoding="utf-8", errors="replace") as f:
            return f.read().splitlines()
    except OSError:
        return []


def describe(p, lines):
    ext = os.path.splitext(p)[1]
    if ext in (".luau", ".lua"):
        for l in lines[:40]:
            s = l.strip()
            if s.startswith("--") and not s.startswith("--!") and len(s) > 4 and not set(s) <= set("-= "):
                return s.lstrip("-").strip()
    if ext == ".py":
        first = next((l.strip() for l in lines if l.strip() and not l.startswith("#")), "")
        if first.startswith(('"""', "'''")):   # module docstring only, never a function's
            t = first[3:].rstrip("\"'").strip()
            if t:
                return t
        for l in lines[:20]:
            if l.strip().startswith("#") and not l.startswith("#!"):
                return l.strip("# ").strip()
    if ext == ".md":
        for l in lines:
            if l.startswith("#"):
                return l.lstrip("# ").strip()
    return ""


def symbols(p, lines):
    ext = os.path.splitext(p)[1]
    out = []
    for i, l in enumerate(lines, 1):
        if ext in (".luau", ".lua"):
            m = re.match(r"^(?:local\s+)?function\s+([\w.:]+)\s*\(", l)
            if m:
                out.append(f"{m.group(1)}:{i}")
            m = re.match(r"^\t?([A-Z][A-Z0-9_]{3,})\s*=\s*\{", l)       # top-level registry keys (content tables)
            if m and len(out) < MAX_SYMBOLS * 3:
                out.append(f"{m.group(1)}:{i}")
        elif ext == ".py":
            m = re.match(r"^(def|class)\s+(\w+)", l)
            if m:
                out.append(f"{m.group(2)}:{i}")
        elif ext == ".md":
            m = re.match(r"^(#{2,3})\s+(.+)", l)
            if m:
                out.append(f"{m.group(2).strip()[:60]}:{i}")
    if len(out) > MAX_SYMBOLS:
        out = out[:MAX_SYMBOLS] + [f"... +{len(out) - MAX_SYMBOLS} more"]
    return out


def build():
    files = tracked()
    dates = last_changed()
    rows, binaries = [], {}
    for p in files:
        ext = os.path.splitext(p)[1].lower()
        if ext not in TEXT:
            binaries.setdefault(os.path.dirname(p), []).append(os.path.basename(p))
            continue
        lines = read(p)
        desc = describe(p, lines)
        syms = symbols(p, lines)
        rows.append((p, len(lines), desc, syms, dates.get(p, "new")))
    out = ["# LUCKBOUND — Generated file map", "",
           "> GENERATED by `tools/gen_index.py`. Do not edit by hand. **Do not read this file end to end**: search it",
           "> for a path or `symbol:` and open only that file at that line. Start from `INDEX.md` (the guide).", "",
           f"_{len(rows)} text files, {sum(len(v) for v in binaries.values())} binary assets. Regenerate with "
           "`python tools/gen_index.py`; CI refuses a stale index. Format: `path` (lines) - description; then "
           "`symbol:line` for every function / top-level entry / doc heading. The date after `·` is the file's last "
           "commit (history: `git log --format=\"%cs %s\" -- <path>`)._", ""]
    section = None
    for p, n, desc, syms, day in rows:
        top = "/".join(p.split("/")[:2]) if "/" in p else "(root)"
        if top != section:
            section = top
            out += ["", f"### {top}", ""]
        line = (f"- `{p}` ({n}) - {desc}" if desc else f"- `{p}` ({n})") + f" \u00b7 {day}"
        out.append(line)
        if syms:
            out.append(f"  - `{os.path.basename(p)}`: " + ", ".join(syms))
    out += ["", "### Binary assets (by folder)", ""]
    for d in sorted(binaries):
        names = binaries[d]
        shown = ", ".join(names[:30]) + (f", ... +{len(names) - 30}" if len(names) > 30 else "")
        out.append(f"- `{d}/` ({len(names)}): {shown}")
    return "\n".join(out) + "\n"


def main():
    new = build()
    try:
        with open(MAP, encoding="utf-8") as f:
            old = f.read()
    except OSError:
        old = ""
    if "--check" in sys.argv:
        # dates are not compared: a file's date only exists once its commit does (index.yml writes them on main)
        if DATE.sub("", new) != DATE.sub("", old):
            print("INDEX_MAP.md is stale: run `python tools/gen_index.py` and commit the result.")
            import difflib
            for d in list(difflib.unified_diff(old.splitlines(), new.splitlines(), lineterm="", n=0))[:40]:
                print(d)
            sys.exit(1)
        print("INDEX_MAP.md is up to date.")
        return
    with open(MAP, "w", encoding="utf-8", newline="\n") as f:
        f.write(new)
    print("INDEX_MAP.md regenerated.")


if __name__ == "__main__":
    main()
