"""Publish generated content from live_delivery.json, without touching Blender."""
import json
import math
import re
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'assets/export/worlds/ethereal_scape'


def lua(v):
    if isinstance(v, dict):
        return '{' + ','.join('[' + json.dumps(k) + ']=' + lua(x) for k,x in v.items()) + '}'
    if isinstance(v, list): return '{' + ','.join(lua(x) for x in v) + '}'
    if isinstance(v, bool): return 'true' if v else 'false'
    if isinstance(v, float):
        assert math.isfinite(v)
        return format(v, '.7g')
    return json.dumps(v)


def main():
    data = json.loads((OUT / 'live_delivery.json').read_text())
    # Derive export bookkeeping for deliveries produced before it was recorded per part.
    exported = {a['Export'].lower(): a for a in data['Audit'] if 'Triangles' in a}
    for parts in data['Parts'].values():
        for part in parts:
            name = part['AssetKey'][3:].lower()
            part['Object'] = exported[name]['Export']
            part['Triangles'] = exported[name]['Triangles']
    for rows in data['Placements'].values():
        for row in rows:
            if '_canopy_' in row['Prop'] and 'curved_chair' not in row['Prop']:
                row['Anim'] = 'Foliage'
                row['Hinge'] = [0, -row['S'][1]/2, 0]
    chunk_path = ROOT / 'src/shared/Content/Chunks/EtherealScape.luau'
    text = chunk_path.read_text(encoding='utf-8').split('-- LIVE DELIVERY')[0]
    text = re.sub(r'return out\s*$', '', text)
    runtime = {}
    room_id = 'ES_SHRINE_MINIBOSS_ROOM'
    for id, parts in data['Parts'].items():
        if id != room_id:
            runtime[id] = {'MeshParts': parts}
            if id in data['Boundaries']: runtime[id]['Boundary'] = data['Boundaries'][id]
            if id.startswith('ES_BACKDROP_'): runtime[id]['Motion'] = 'Float'
    fixtures = {r['Fixture']['Object']: r['Fixture'] for r in data['Audit'] if 'Fixture' in r}
    gate = fixtures['ES_SHRINE_VAULT_GATE_PROP_01']
    door = fixtures['ES_SHRINE_VAULT_DOOR_PROP_01']
    room = dict(Id=room_id, WorldId='ETHEREAL_SCAPE', Role='MINIBOSS', Offset=[0,4096,0],
        AssetKey=data['Parts'][room_id][0]['AssetKey'], SizeX=144, SizeY=256, SizeZ=232,
        GroundOffsetY=96, MeshYawOffset=180, Sockets=[], MeshParts=data['Parts'][room_id],
        Portal=dict(SourceP=[0,12,24], SourceS=[17.5,23.8,4], SourceArrival=[0,4,34],
                    RoomP=[0,12,105], RoomS=[18,23.5,4], RoomArrival=[0,4,96]),
        Gate=dict(Mesh=gate['Prop'], P=gate['P'], S=gate['S'], TravelY=26.1, RequiredStageState='BossDefeated'))
    runtime['ES_CAP_SEALED_SHRINE']['AttachedRooms'] = [room]
    text += '-- LIVE DELIVERY: generated by tools/prepare_ethereal_delivery.py\n'
    text += 'local live = ' + lua(runtime) + '\n'
    text += 'for _, chunk in out do\n local detail = live[chunk.Id]\n if detail then\n for k,v in detail do chunk[k]=v end\n end\nend\nreturn out\n'
    chunk_path.write_text(text, encoding='utf-8', newline='\n')
    props_path = ROOT / 'src/shared/Content/Props/EtherealScape.luau'
    props = props_path.read_text(encoding='utf-8').split('-- LIVE DELIVERY')[0]
    props = props.replace('return {', 'local set = {', 1)
    if 'local set = {' not in props: raise ValueError('Unknown prop content format')
    props += '\n-- LIVE DELIVERY: generated by tools/prepare_ethereal_delivery.py\n'
    props += 'local live = '+lua(data['Placements'])+'\n'
    props += 'for id, rows in live do\n set.Placements[id] = set.Placements[id] or {}\n'
    bank_root = ET.parse(ROOT / 'assets/rbxm/props/CLOUD_BANKS.rbxmx').getroot()
    bank_rows = []
    for item in bank_root.iter('Item'):
        if item.get('class') == 'MeshPart':
            name = item.findtext('./Properties/string[@name="Name"]')
            size = item.find('./Properties/Vector3[@name="size"]')
            x,y,z = (float(size.findtext(axis)) for axis in ('X','Y','Z'))
            bank_rows.append(dict(Name=name,Y=y/x,Z=z/x))
    props += 'for _, row in rows do table.insert(set.Library,row.Prop); table.insert(set.Placements[id],row) end\nend\nlocal banks = BANKDATA\nfor _, bank in banks do table.insert(set.Library, bank.Name) end\nlocal ids = {}\nfor id in set.Placements do table.insert(ids, id) end\ntable.sort(ids)\nfor index, id in ids do\n local kept, cloudCount = {}, 0\n for _, row in set.Placements[id] do\n  if row.Prop == "prop_es_cloud_a" or row.Prop == "prop_es_cloud_b" then\n   cloudCount += 1\n   -- One bank on alternating chunks: air and architecture stay readable.\n   if index % 2 == 0 and cloudCount == 1 then\n    local bank = banks[index % #banks + 1]\n    row.Prop, row.Anim = bank.Name, "Drift"\n    row.S = {row.S[1], row.S[1] * bank.Y, row.S[1] * bank.Z}\n    table.insert(kept, row)\n   end\n  else table.insert(kept, row) end\n end\n set.Placements[id] = kept\nend\nreturn set\n'.replace('BANKDATA', lua(bank_rows))
    props_path.write_text(props, encoding='utf-8', newline='\n')
    fixture_path = ROOT / 'src/shared/Content/Fixtures/EtherealScape.luau'
    fixtures_text = fixture_path.read_text(encoding='utf-8').split('-- LIVE DELIVERY')[0].replace('return {','local set = {',1)
    vault = dict(Kind='VAULT', RequiredStageState='BossDefeated', P=door['P'], R=[1,0,0,0,1,0,0,0,1],
                 Parts=[dict(Mesh=door['Prop'],Role='Door',P=[0,0,0],S=door['S'])])
    fixtures_text += '\n-- LIVE DELIVERY: generated by tools/prepare_ethereal_delivery.py\n'
    fixtures_text += 'table.insert(set.Library,'+lua(door['Prop'])+')\n'
    fixtures_text += 'set.Placements.'+room_id+' = {'+lua(vault)+'}\nreturn set\n'
    fixture_path.write_text(fixtures_text, encoding='utf-8', newline='\n')
    manifest_path = ROOT / 'src/shared/Content/AssetManifest.luau'
    manifest = manifest_path.read_text(encoding='utf-8')
    keys = sorted({p['AssetKey'] for parts in data['Parts'].values() for p in parts})
    entries = ''
    for key in keys:
        if re.search(r'\b'+re.escape(key)+r'\s*=\s*{',manifest): continue
        entries += '\t'+key+' = {\n\t\tAssetId = "",\n\t\tStatus = "PLACEHOLDER",\n\t\tSource = "assets/export/worlds/ethereal_scape/ethereal_scape_structure.fbx",\n\t},\n'
    manifest = manifest.replace('local ENTRIES: { [string]: AssetEntry } = {',
                                 'local ENTRIES: { [string]: AssetEntry } = {\n'+entries,1)
    manifest_path.write_text(manifest,encoding='utf-8',newline='\n')
    (OUT / 'ethereal_scape_structure.json').write_text(json.dumps(data['Parts'],indent=2),encoding='utf-8')
    (OUT / 'live_delivery.json').write_text(json.dumps(data,indent=2),encoding='utf-8')
    print(f'Published {len(keys)} structure assets; 41 random-kit pieces + one conditional room; 35 boundary groups')


if __name__ == '__main__': main()
